# Generated by Django 5.0 on 2025-12-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
