# Generated by Django 5.0 on 2025-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_voter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='middlename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='aadhaar_hash',
            field=models.CharField(default='000000000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
    ]
