# Generated by Django 5.0 on 2025-12-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_voter_middlename_alter_voter_aadhaar_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='voter',
            name='identity_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('voter_id', 'Voter ID Card'), ('passport', 'Passport')], default='aadhaar', max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='aadhaar_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address',
            field=models.TextField(),
        ),
    ]
