# Generated by Django 5.0 on 2025-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_voter_age_voter_identity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='photo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
