# Generated by Django 5.0 on 2025-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_voter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='voters/'),
        ),
    ]
