# Generated by Django 5.0 on 2025-12-25 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('max_vote', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=150)),
                ('platform', models.TextField()),
                ('party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('party_symbol', models.CharField(blank=True, max_length=150, null=True)),
                ('aadhaar_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.position')),
            ],
        ),
    ]
