# Generated by Django 5.0 on 2025-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='identity_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='identity_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('voter_id', 'Voter ID Card'), ('passport', 'Passport')], default='aadhaar', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_type',
            field=models.CharField(choices=[('party', 'Political Party'), ('independent', 'Independent')], default='independent', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/symbols/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/photos/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='platform',
            field=models.TextField(blank=True, null=True),
        ),
    ]
