# Generated by Django 5.0 on 2025-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_address_candidate_candidate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Voting System', max_length=100)),
            ],
        ),
    ]
