# Generated by Django 5.0 on 2025-12-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='platform',
            new_name='manifesto',
        ),
    ]
